# Generated by Django 4.1 on 2023-08-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="People",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("person", models.CharField(max_length=250)),
                ("pic", models.ImageField(upload_to="pics")),
                ("detail", models.TextField()),
            ],
        ),
    ]
